### ISSUE TITLE
求教

### ISSUE THREAD

**Issue by 1128qx** [AaronFang123/Naive-Bayes-classifier#2]
这边有几个小问题想向您请教一下，不知道您方便吗？

**Comment by nado-dev** [comment]
这个仓库是我两年前做课程实验时留下的，做得很粗糙，我现在不做机器学习了仓库也已经不维护了，你可以看看我刚传上来的实验报告 report.doc

**Comment by 1128qx** [comment]
我是有一些很低级的问题想问问您，我数据集下载了，然后运行代码错误，所以想问问代码是否有地方需要修改。还是很谢谢您！

**Comment by nado-dev** [comment]
刚刚跑了一下，代码是没问题的
![image](https://user-images.githubusercontent.com/48375763/159437202-080e5cb7-84fc-4742-b885-e0f3d58c936e.png)
是不是你的环境有问题

**Comment by 1128qx** [comment]
你好，我还有一些小问题想请教一下，如果您方便的话，我们可以加一下吗？谢谢

**Comment by nado-dev** [comment]
QQ 1332752797
