### ISSUE TITLE
在拉普拉斯平滑时我发现了一点小的错误

### ISSUE THREAD

**Issue by adorablely** [AaronFang123/Naive-Bayes-classifier#3]
我认真阅读了你的代码，并测试了它，发现一点小的错误
# 拉普拉斯平滑
        word_occurs_counts_ham = _train_word_dict[word][0]
        # 出现过这个词的信件数 / 垃圾邮件数
        ham_probability += math.log((float(word_occurs_counts_ham) + 1) / _ham_count + 2)

        word_occurs_counts_spam = _train_word_dict[word][1]
        # 出现过这个词的信件数 / 普通邮件数
        spam_probability += math.log((float(word_occurs_counts_spam) + 1) / _spam_count + 2)
在这里_spam_count + 2 应该为（_spam_count + 2）

**Comment by nado-dev** [comment]
非常感谢，已经修改
